### ISSUE TITLE
TabPane weird behaviour after enabling TabClosingPolicy

### ISSUE THREAD

**Issue by AnimusXov** [sshahine/JFoenix#1180]
So this how tabpane (it's wrapped in StackPane) looks like after adding two tabs with `setClosable(false)`. Custom CSS is fine here.
![java_G6kLbOMS1g](https://user-images.githubusercontent.com/22781114/106953588-768a6200-672a-11eb-8f63-20e0f54367ee.png)
After adding a new tab without  `setClosable(false)` it doesn't care my custom css also positioning breaks as well.
Do I have reapply style sheet every time I add new tab or what would be a workaround here?

![java_GX1xL15TF7](https://user-images.githubusercontent.com/22781114/106954058-24960c00-672b-11eb-94d2-3be73110a904.png)
There is not happening a lot during adding new tab, just `setText()`. After closing new tab everything goes back to normal.

EDIT: After going through some CSS I think it's a problem at my end, new tab just changes height a bit and places label a bit higher relative to other tabs.

**Comment by sshahine** [comment]
I'll close this issue for now, feel free to reopen if not resolved
