### ISSUE TITLE
JFXButton not showing on JFX Drawer

### ISSUE THREAD

**Issue by jeranio** [sshahine/JFoenix#1184]
I have the drawer functioning as is, no css styling etc. If I add a JFXButton and run the program using Intellij, no buttons show up but if I I add a normal stock Button then the buttons show up. I have added JFoenix libs to my project structure.

Sorry using JDK 15, JFoenix 9.0.10. I have tried using other JDK but my app throws all sorts of errors. The combination I have now works or runs all my other packages in the same app fine.

**Comment by sshahine** [comment]
Can you provide SSCCE for the issue? also feel free to take a loot at my other repo [JFXBase](https://github.com/sshahine/JFXBase/blob/master/build.gradle) build file, it has the full list of needed exports/opens

**Comment by jeranio** [comment]
Aye, sorry this was raised over a month ago and I have since either resolved it or moved on. I did however manage to get a lot of insight from this post which I would say helped a lot.

[https://stackoverflow.com/questions/62407413/javafx-jfxdrawer-not-hidden-completely-when-program-starts]

My drawer is working now as I expect it, resolving other issues related to the drawer like I need it not to shrink my existing stage but instead go over it and hide the background.
