### ISSUE TITLE
SceneBuilder blocking drag & drop of some JFX components.

### ISSUE THREAD

**Issue by WesleyWong420** [sshahine/JFoenix#1201]
I am having issue where SceneBuilder doesn't allow the insertion of some components such as JFXTextFields and JFXPasswordField, when I tried to drag it in, mouse cursor will have a round error block logo. However, component like JFXTextArea have no problem of dragging in. 

SceneBuilder version: 16
JFoenix version: Java 9

**Comment by iamMHZ** [comment]
@WesleyWong420   Have you found any solution?  I am having the same problem with some components. :(

**Comment by IndiTheo** [comment]
Same problem
