### ISSUE TITLE
JFXChipView Make Chip Editable

### ISSUE THREAD

**Issue by usama-shiranai90** [sshahine/JFoenix#1212]
it is possible to edit or change a chip once it has been set on JFXChipView.
![2021-08-15_15-45-19](https://user-images.githubusercontent.com/53114169/129475852-cf3ae4c5-6460-4107-b2c6-1daf369a7628.jpg)

**Comment by sshahine** [comment]
Yes, it's doable, you need to create a custom chip that allows editing the content instead of using the default chip.
