### ISSUE TITLE
gridpane hide line question

### ISSUE THREAD

**Issue by Lson-L** [sshahine/JFoenix#1214]
Hi,
I want create a gridpane to edit something like this 
![image](https://user-images.githubusercontent.com/77139715/131426829-074fdc5e-b683-47bd-be2c-268308594e57.png)
when i change type comboBox,i want hide label line like this 
![image](https://user-images.githubusercontent.com/77139715/131426922-2bf72261-f9a8-47a8-8c10-4f2b781703c3.png)
but the white space is still here.
How Can i do is right?

**Comment by sshahine** [comment]
Will close this issue, as it's not related to JFoenix

**Comment by sshahine** [comment]
a quick response, change the managed state of the node, not just its visibility
