### ISSUE TITLE
Style the icons in JavaFx when  use ":selected" is not working?

### ISSUE THREAD

**Issue by salmantln** [sshahine/JFoenix#1216]
Style the icons in JavaFx when  use ":selected" is not working? Or am i doing something wrong. I try using 

".button .ikonli-font-icon:selected {
    -fx-icon-code: "gmi-file-download";
    -fx-icon-color: red;
    -fx-icon-size: 20px;
}" in my stylesheet but it doesn't seem to work.

**Comment by sshahine** [comment]
You need to manually handle adding / removing the "selected" pseudo class to your icon, else that won't work.
